name: CI

on: [push]

jobs:
  build:
    name: Build & test on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Windows - setup MSBuild
      if: startsWith(matrix.os, 'windows')
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0,18.0)'

    - name: Windows - building the binary
      if: startsWith(matrix.os, 'windows')
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        call "update_repository.bat"
        call "%programfiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        msbuild /t:Build /p:Configuration=Release;PlatformToolset=v143